name: "bluebell"
mode: "dev"
version: "v0.0.1"
port: 8080
log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  user: "root"
  password: "123456"
  dbname: "bluebell"
  port: 13306
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  password: ""
  port: 16379
  db: 0
  pool_size: 100